# Inversion Constraints

The constraints transform an ill-posed problem into a well-posed problem. So, we formulate a constrained non-linear inversion by summing constraints to the misfit function $\Psi (\textbf{m})$. 

\begin{equation}
\Gamma (\textbf{m}) = \Psi (\textbf{m}) + \mu \sum\limits^{6}_{j=1}\alpha_{j}\varphi_{j}(\textbf{m})$
\end{equation}

where $\textbf{m}$ is the parameter vector, $\varphi_{j}$ is the $j$th constraint, $\alpha_{j}$ is the $j$-th is a positive scalar that defines the weight of the $j$-th constraint and $\mu$ is a positive scalar called regularization parameter. To solve this problem we will use the Levenberg-Marquadt method.

In this code, we impose six constraints to an Hessian matrix and parameter vector. The functions are tested in some special cases.

### Impor required library

In [3]:
import numpy as np
import polyprism_tests as tests

### Import my functions from an external file

In [4]:
import mag_polyprism_functions as mfun

### Input

In [2]:
M = 6 # number of vertices
L = 2 # number of prisms
P = L*(M+2) # number of parameters

In [6]:
alpha = 1.0 # weight

In [4]:
H = np.zeros((P,P)) # Hessian matrix

In [ ]:
m = np.zeros(P) # parameter vector

### Constraints

Here we describe the constraints and the result from its functions.

### Smoothness constraint on the adjacent radial distances within each prism $\varphi_{1}(\textbf{m})$

Smoothness constraint on the estimated radial distances within each prism. This constraint imposes that the $j$-th radial distance of the $k$-th prism $r^{k}_{j}$ must be close to the adjacent one $r^{k}_{j+1}$ within the same $k$-th prism. It prevents descontinuity on the estimated radial distances within each prism and imposes a cylindrical shape to the prisms. So, the squared Euclidian Norm of the difference between the adjacent radial distances must be minimun:

\begin{equation}
\varphi_{1}(\textbf{m}) = \sum\limits^{L}_{k=1}\left[\left(r^{k}_{M}-r^{k}_{1}\right)^2 + \sum\limits^{M-1}_{j=1}\left(r^{k}_{j}-r^{k}_{j+1}\right)^2\right]
\end{equation}

For simplicity we rewrite the equation above with matrix notation. This constraint will be:

\begin{equation}
\varphi_{1}(\textbf{m}) = \textbf{m}^{T}\textbf{R}^{T}_{1}\textbf{R}_{1}\textbf{m}
\end{equation}

where

\begin{equation}
\textbf{R}_{1} = 
\begin{bmatrix}
\textbf{R}^{\sharp} & 0 & \cdots & 0 \\
0 & \textbf{R}^{\sharp} &  \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 &  \cdots & \textbf{R}^{\sharp} \\
\end{bmatrix}_{ML\times P}
\end{equation}

while

\begin{equation}
\textbf{R}^{\sharp} = 
\begin{bmatrix}
1 & -1 & 0 & \cdots & 0 & 0 & 0 & 0 \\
0 & 1 & -1 & \cdots & 0 & 0 & 0 & 0 \\
\vdots & \vdots & \vdots & & \vdots & \vdots & \vdots & \vdots\\
0 & 0 & 0 & \cdots & 1 & -1 & 0 & 0 \\
-1 & 0 & 0 & \cdots & 0 & 1 & 0 & 0 \\
\end{bmatrix}_{M(L-1)\times P}
\end{equation}

In [7]:
H = mfun.Hessian_phi_1(M,L,H,alpha)

In [8]:
print H

[[ 2. -1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0. -1.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2. -1.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [9]:
tests.test_Hessian_phi_1()

In [10]:
d1 = np.diag(H)
d2 = np.diag(H, k=1)
d3 = np.diag(H, k=-1)
d4 = np.diag(H, k=M-1)
d5 = np.diag(H, k=-M+1)

In [21]:
y = np.ones(P)

In [22]:
z0 = np.ones(P)
z1 = np.ones(M+2)
z2 = np.ones(P-1)

In [23]:
y *= z0
y[:M+2] *= z1
y[:P-1] *= z2

In [24]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])