In [1]:
import numpy as np
import mag_polyprism_functions as mfun
import polyprism_tests as tests

C:\Users\Vanderlei\Documents\fatiando\fatiando\vis\mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")


In [2]:
M = 5
L = 1
P = L*(M+2)

In [3]:
P

7

In [4]:
H = np.zeros((P,P))

In [5]:
print H

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [6]:
alpha = 1.0

In [8]:
H = mfun.Hessian_phi_1(M,L,H,alpha)

In [9]:
print H

[[ 2. -1.  0.  0. -1.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.]
 [-1.  0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [10]:
tests.test_phi_1()