In [1]:
import numpy as np
import mag_polyprism_functions as mfun
import polyprism_tests as tests

/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")


In [2]:
M = 3
L = 2
P = L*(M+2)

In [3]:
P

10

In [4]:
H = np.zeros((P,P))

In [5]:
print H

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [6]:
alpha = 1.0

In [7]:
H = mfun.Hessian_phi_2(M,L,H,alpha)

In [8]:
print H

[[ 1.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [9]:
tests.test_Hessian_phi_2()

In [10]:
d1 = np.diag(H)
d2 = np.diag(H, k=M+2)
d3 = np.diag(H, k=-M-2)

In [11]:
y = np.arange(1.0, P + 1.0)

In [12]:
p1 = y*d1
p2 = y[M+2:]*d2
p3 = y[:P-M-2]*d3

In [13]:
p2 = np.hstack((p2, np.zeros(M+2)))
p3 = np.hstack((np.zeros(M+2), p3))

In [14]:
p = p1 + p2 + p3

In [15]:
pdot = np.dot(H,y)

In [16]:
pf = mfun.gradient_phi_2(M,L,y,alpha)

In [17]:
np.allclose(pdot,pf)

True