In [1]:
import numpy as np
import mag_polyprism_functions as mfun
import polyprism_tests as tests

/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")


In [2]:
M = 3
L = 1
P = L*(M+2)

In [3]:
P

5

In [4]:
i, j = np.diag_indices(P)

In [5]:
print i

[0 1 2 3 4]


In [6]:
print j

[0 1 2 3 4]


In [7]:
for k in range(0,P,M+2):
    print 'i = ', i[k:k+M-1], 'j+1 = ', j[k:k+M-1]+1

i =  [0 1] j+1 =  [1 2]


In [8]:
alpha = 1.0

In [9]:
H = np.zeros((P,P))

In [10]:
H = mfun.Hessian_phi_4(M,L,H,alpha)

In [11]:
print H

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [12]:
H_ref = np.zeros((P,P)) # hessian for comparison
H_ref[-1,-1] = alpha
H_ref[-2,-2] = alpha
H_ref

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [13]:
tests.test_Hessian_phi_4()

In [14]:
d1 = np.diag(H)

In [15]:
y = np.arange(1.0, P + 1.0)

In [16]:
m1 = y[M:M+2]*d1[M:M+2]

In [17]:
m = np.hstack((np.zeros(M), m1, np.zeros(P-M-2)))

In [18]:
pdot = np.dot(H,y)

In [21]:
p3 = mfun.gradient_phi_4(M,L,y,np.zeros(2),alpha)

In [22]:
np.allclose(m,pdot,p3)

True