In [1]:
import numpy as np

In [2]:
M = 3
L = 2
P = L*(M+2)

In [3]:
P

10

In [4]:
i, j = np.diag_indices(P)

In [5]:
print i

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print j

[0 1 2 3 4 5 6 7 8 9]


In [7]:
for k in range(0,P,M+2):
    print 'i = ', i[k:k+M-1], 'j+1 = ', j[k:k+M-1]+1

i =  [0 1] j+1 =  [1 2]
i =  [5 6] j+1 =  [6 7]


In [8]:
alpha = 1.0

In [9]:
H = np.zeros((P,P))

H[M,M+1] = 1.*alpha
H[M+1,M] = 1.*alpha

In [10]:
print H

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
