In [1]:
import numpy as np

In [2]:
M = 3
L = 3
P = L*(M+2)

In [3]:
P

15

In [13]:
#i, j = np.diag_indices(P)
i, j = np.diag_indices(M+2)

In [14]:
print i

[0 1 2 3 4]


In [15]:
print j

[0 1 2 3 4]


In [7]:
for k in range(0,P,M+2):
    print 'i = ', i[k:k+M-1], 'j+1 = ', j[k:k+M-1]+1

i =  [0 1] j+1 =  [1 2]
i =  [5 6] j+1 =  [6 7]
i =  [10 11] j+1 =  [11 12]


In [8]:
alpha = 1.0

In [16]:
H = np.zeros((P,P))

#for k in range(M+2):
#    H[k,k] += 1.*alpha

H[i,j] = alpha

In [17]:
print H

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
