In [1]:
import numpy as np
import mag_polyprism_functions as mfun
import polyprism_tests as tests

/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")


In [2]:
M = 3
L = 1
P = L*(M+2)

In [3]:
P

5

In [9]:
H = np.zeros((P,P))

In [10]:
print H

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [11]:
alpha = 1.0

In [12]:
H = mfun.phi_5(M,L,H,alpha)

In [13]:
print H

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [14]:
tests.test_phi_5()