# Tests for

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy
from __future__ import division
from fatiando import mesher, gridder, utils
from fatiando.gravmag import polyprism
from fatiando.mesher import PolygonalPrism
from fatiando.gravmag import prism
from fatiando.mesher import Prism
from fatiando.vis import mpl, myv
from fatiando.constants import CM, T2NT
from matplotlib import colors, ticker, cm
import mag_polyprism_functions as mfun
import polyprism_tests as tests
% matplotlib inline

/home/leonardo/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")
/home/leonardo/anaconda2/lib/python2.7/site-packages/fatiando/vis/myv.py:51: UserWarning: This module will be removed in v0.7.
  warnings.warn("This module will be removed in v0.7.")


In [2]:
M = 3
L = 3
P = L*(M+2)
alpha = 1.
H = np.zeros((P,P))

In [3]:
m0 = np.zeros(M+2)
H = mfun.Hessian_phi_5(M,L,H,alpha)
print H

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  2.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  2.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.]]


In [4]:
m = np.arange(5., P+5., 1.) # gradient
m1 = m.copy()
print m1

[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]


In [5]:
m3 = np.zeros(P)
m0 = np.ones(M+2)
# calculating the product between the diagonals and the slices of m
m3[:M+2] = (m[:M+2] - m0)*alpha
    
phi_3 = np.dot(m3, m)


print m
print m3
print phi_3

[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
[ 4.  5.  6.  7.  8.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
220.0


In [6]:
grad = mfun.gradient_phi_1(M,L,m1,alpha)
phi = mfun.phi_1(M,L,m1,alpha)
print grad
print phi
print m1

[  2.   6.  10.   8.   9.   7.  11.  15.  13.  14.  12.  16.  20.  18.  19.]
18.0
[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]


In [7]:
tests.test_diags_phi_1()

In [8]:
tests.test_diags_phi_2_tp()

In [9]:
tests.test_diags_phi_2_mp()

In [10]:
tests.test_diags_phi_5_tp()

In [11]:
tests.test_diags_phi_5_mp()

In [12]:
tests.test_diags_phi_6()

In [13]:
tests.test_gradient_phi_1_unitary()

In [14]:
tests.test_gradient_phi_1_arranged()

In [15]:
tests.test_gradient_phi_2_unitary()

In [16]:
tests.test_gradient_phi_2_arranged()

[ -4.  -3.  -2.   4.   5.  11.  12.  13.   9.  10.]
[ -4.  -3.  -2.   4.   5.  11.  12.  13.   9.  10.]


In [17]:
tests.test_gradient_phi_3()

In [18]:
tests.test_gradient_phi_4()

In [19]:
tests.test_gradient_phi_5_unitary()

In [20]:
tests.test_gradient_phi_5_arranged()

In [21]:
tests.test_gradient_phi_6()

In [22]:
tests.test_phi_1_arranged()

In [23]:
tests.test_phi_2_arranged()

In [24]:
tests.test_phi_3_arranged()

In [25]:
tests.test_phi_4_arranged()

In [26]:
tests.test_phi_5_arranged()

In [27]:
tests.test_phi_6_arranged()

597.0
597.0
