# Tests for

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy
from __future__ import division
from fatiando import mesher, gridder, utils
from fatiando.gravmag import polyprism
from fatiando.mesher import PolygonalPrism
from fatiando.gravmag import prism
from fatiando.mesher import Prism
from fatiando.vis import mpl, myv
from fatiando.constants import CM, T2NT
from matplotlib import colors, ticker, cm
import mag_polyprism_functions as mfun
import polyprism_tests as tests
% matplotlib inline

/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")
/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/myv.py:51: UserWarning: This module will be removed in v0.7.
  warnings.warn("This module will be removed in v0.7.")


In [2]:
M = 3
L = 3
P = L*(M+2)
alpha = 1.
H = np.zeros((P,P))

In [3]:
H = mfun.Hessian_phi_5(M,L,H,alpha)
print H

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  2.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  2.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.]]


In [4]:
m = np.arange(1., P+1., 1.) # gradient

print m

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.]


In [5]:
grad = mfun.gradient_phi_6(M,L,m,alpha)
print grad
print m

[  2.   4.   6.   4.   5.  12.  14.  16.   9.  10.  22.  24.  26.  14.  15.]
[  2.   4.   6.   4.   5.  12.  14.  16.   9.  10.  22.  24.  26.  14.  15.]


In [6]:
tests.test_diags_phi_1()

In [7]:
tests.test_diags_phi_2_tp()

In [8]:
tests.test_diags_phi_2_mp()

In [9]:
tests.test_diags_phi_5_tp()

In [10]:
tests.test_diags_phi_5_mp()

In [11]:
tests.test_diags_phi_6()

In [12]:
tests.test_gradient_phi_1_unitary()

In [13]:
tests.test_gradient_phi_1_arranged()

In [14]:
tests.test_gradient_phi_2_unitary()

In [15]:
tests.test_gradient_phi_2_arranged()

In [16]:
tests.test_gradient_phi_3()

In [17]:
tests.test_gradient_phi_4()

In [18]:
tests.test_gradient_phi_5_unitary()

In [19]:
tests.test_gradient_phi_5_arranged()

In [20]:
tests.test_gradient_phi_6()