# Plot convergence curves

In [1]:
import matplotlib as mpb

# show all the matplotlib backends 
mpb.rcsetup.all_backends 

# force matplotlib to use the 'Qt5Agg' backend 
mpb.use(arg='Qt5Agg', force=True)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cPickle as pickle
import scipy.stats as sp
import os

from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from fatiando.vis import mpl
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

/home/leo/anaconda2/lib/python2.7/site-packages/fatiando/vis/mpl.py:76: UserWarning: This module will be removed in v0.6. We recommend the use of matplotlib.pyplot module directly. Some of the fatiando specific functions will remain.
  "specific functions will remain.")


In [3]:
import sys
sys.path.insert(0, '../../code')

import mag_polyprism_functions as mfun
import mag_sphere_functions as msf

In [4]:
mypath = 'data/real_obs_pts/tfa_inversion/multiple_int_min9_int_max15_z0_min-400_z0_max-200_r800_dz650_V15_L10Feb-10-2020/'

In [5]:
with open(mypath+'inversion.pickle') as w:
        di = pickle.load(w)

In [6]:
with open('data/model_real_obs_pts.pickle') as w:
        model = pickle.load(w)

In [7]:
plt.figure(figsize=(10,10))
plt.title('Convergence', fontsize = 18)
plt.xlabel('Iteration number')
for i, phi in enumerate(di['results']):
    plt.plot(phi[3], label='inversion%d' % (i+1))
plt.legend(loc=0, fontsize=2.5, shadow=bool, framealpha=1)

plt.savefig(mypath+'_tfa_convergence.png', dpi=300, bbox_inches="tight")
plt.show()

In [8]:
z0 = di['z0']
intensity = di['intensity']
z0_plot, int_plot = np.meshgrid(z0, intensity)
z0_plot = z0_plot.ravel()
int_plot = int_plot.ravel()
n = z0.size
m = intensity.size
N = di['x'].size

In [9]:
matrix_gamma = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        matrix_gamma[i, j] = di['results'][i*n+j][3][-1]

In [10]:
di['regularization']

array([1.e-04, 1.e-04, 0.e+00, 0.e+00, 1.e-04, 1.e-07, 1.e-04])

In [11]:
matrix_phi = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        matrix_phi[i, j] = np.linalg.norm(di['results'][i*n+j][6][-1], 2)**2./N

In [12]:
fig, ax = fig, ax = plt.subplots(1,1)
w = 3
img = ax.imshow(matrix_gamma, vmin=0, vmax=2000, origin='lower',extent=[0,w,0,w])
plt.ylabel('$z_0$ (m)')
plt.xlabel('$m_0$ (A/m)')
plt.plot(1.5, 1.5, '^r', markersize=12)
plt.plot(1.25, 1.25, 'Dc', markersize=12, linewidth=2)
x_label_list = []
y_label_list = []
for xl, yl in zip(intensity,z0):
    x_label_list.append(str(xl))
    y_label_list.append(str(yl)[:-2])
ax.set_xticks(np.linspace(w/(2.*n), w - w/(2.*n), n))
ax.set_yticks(np.linspace(w/(2.*m), w - w/(2.*m), m))
ax.set_xticklabels(x_label_list)
ax.set_yticklabels(y_label_list)
# Minor ticks
ax.set_xticks(np.linspace(0, w, n+1), minor=True);
ax.set_yticks(np.linspace(0, w, m+1), minor=True);
ax.grid(which='minor', color='k', linewidth=2)
plt.colorbar(img)
plt.savefig(mypath+'complex_obj_func_map.png', dpi=300, bbox_inches="tight")
plt.show()

In [13]:
fig, ax = fig, ax = plt.subplots(1,1)
w = 3
img = ax.imshow(matrix_phi, vmin=0, vmax=2000, origin='lower',extent=[0,w,0,w])
plt.ylabel('$z_0$ (m)')
plt.xlabel('$m_0$ (A/m)')
x_label_list = []
y_label_list = []
for xl, yl in zip(intensity,z0):
    x_label_list.append(str(xl))
    y_label_list.append(str(yl)[:-2])
ax.set_xticks(np.linspace(w/(2.*n), w - w/(2.*n), n))
ax.set_yticks(np.linspace(w/(2.*m), w - w/(2.*m), m))
ax.set_xticklabels(x_label_list)
ax.set_yticklabels(y_label_list)
# Minor ticks
ax.set_xticks(np.linspace(0, w, n+1), minor=True);
ax.set_yticks(np.linspace(0, w, m+1), minor=True);
ax.grid(which='minor', color='k', linewidth=2)
plt.colorbar(img)
plt.savefig(mypath+'complex_misfit_func_map.png', dpi=300, bbox_inches="tight")
plt.show()

In [14]:
mindex = np.argwhere(matrix_gamma<150.)
mindex

array([[2, 2],
       [3, 3]])

In [15]:
for re in mindex:
    print re[0]*6 + re[1]
    print matrix_gamma[re[0], re[1]]

14
117.58326245409552
21
86.18882630853872


In [16]:
misdex = np.argwhere(matrix_phi<100.)
misdex

array([[3, 3],
       [3, 4]])

In [17]:
for re in misdex:
    print re[0]*6 + re[1]
    print matrix_phi[re[0], re[1]]

21
47.728472327859336
22
40.62224303851419


# Inversion 3

In [18]:
model0, m0 = mfun.initial_cylinder(15, 10, -300., 300., -320., di['initial_dz'],
                      800., di['main_field'][0], di['main_field'][1],
                      di['main_field'][0], di['main_field'][1], 11.4)

In [19]:
plt.figure(figsize=(6,5))
plt.title('Convergence', fontsize = 18)
plt.xlabel('Iteration number')
plt.plot(di['results'][14][3], 'b-', label='Objective value')
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)
plt.show()

In [20]:
x = di['x']/1000.
y = di['y']/1000.
z = di['z']/1000.

for i in range(len(di['results'][14][2])):
    di['results'][14][2][i].x /= 1000.
    di['results'][14][2][i].y /= 1000.
    di['results'][14][2][i].z1 /= 1000.
    di['results'][14][2][i].z2 /= 1000.
    model0[i].x /= 1000.
    model0[i].y /= 1000.
    model0[i].z1 /= 1000.
    model0[i].z2 /= 1000.
    
for i in model['prisms']:
    i.x /= 1000.
    i.y /= 1000.
    i.z1 /= 1000.
    i.z2 /= 1000.

In [21]:
plt.figure(figsize=(10,10))
ax=plt.subplot(2,2,1)
#plt.title('Residual', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.min(di['results'][14][-2]), vmax=np.min(di['results'][14][-2])*(-1))
plt.tricontourf(di['y'], di['x'], di['results'][14][-2], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(m)', fontsize=10)
plt.ylabel('$x$(m)', fontsize=10)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT', pad=-305)
mpl.m2km()
clb.ax.tick_params(labelsize=13)
inset = inset_axes(ax, width="40%", height="30%", loc=1, borderpad=0.7)
mean = np.mean(di['results'][14][-2])
std = np.std(di['results'][14][-2])
nbins=30
n, bins, patches = plt.hist(di['results'][14][-2],bins=nbins, normed=True, facecolor='blue')
props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
inset.text(0.7, 0.95, "$\mu$ = {:.2f}\n$\sigma$ = {:.2f}".format(mean, std),
                transform=inset.transAxes, fontsize=6,
            va='top', ha='left', bbox=props)
gauss = sp.norm.pdf(bins, mean, std)
plt.plot(bins, gauss, 'k--', linewidth=1., label='Gaussian')


verts_initial = mfun.plot_prisms(model0)
    
verts_true = mfun.plot_prisms(model['prisms'])

verts5 = mfun.plot_prisms(di['results'][14][2])

ax = plt.subplot(2,2,2, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts_initial, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(7, -1, 100)
ax.tick_params(labelsize= 10)
ax.set_ylabel('y (km)', fontsize= 10)
ax.set_xlabel('x (km)', fontsize= 10)
ax.set_zlabel('z (km)', fontsize= 10)
#ax.set_xticklabels(np.linspace(-3, 3, 7))
#ax.set_yticklabels(np.linspace(-3, 3, 7))
#ax.set_zticklabels(np.linspace(0, 2, 9))
#ax.yaxis.labelpad=8
#ax.zaxis.labelpad=8
#ax.xaxis.labelpad=8
ax.view_init(10, 50)

ax = plt.subplot(2,2,3, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts5, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(7, -1, 100)
ax.tick_params(labelsize= 10)
ax.set_ylabel('y (km)', fontsize= 10)
ax.set_xlabel('x (km)', fontsize= 10)
ax.set_zlabel('z (km)', fontsize= 10)
#ax.set_xticklabels(np.linspace(-3, 3, 7))
#ax.set_yticklabels(np.linspace(-3, 3, 7))
#ax.set_zticklabels(np.linspace(0, 2, 9))
#ax.yaxis.labelpad=8
#ax.zaxis.labelpad=8
#ax.xaxis.labelpad=8
ax.view_init(10, 50)

ax = plt.subplot(2,2,4, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts5, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(7, -1, 100)
ax.tick_params(labelsize= 10)
ax.set_ylabel('y (km)', fontsize= 10)
ax.set_xlabel('x (km)', fontsize= 10)
ax.set_zlabel('z (km)', fontsize= 10)
#ax.set_xticklabels(np.linspace(-4, 4, 5))
#ax.set_yticklabels(np.linspace(-3, 3, 7))
#ax.set_zticklabels(np.linspace(0, 2, 9))
ax.yaxis.labelpad=8
ax.zaxis.labelpad=8
ax.xaxis.labelpad=8
ax.view_init(9, -158)

#ax.autoscale_view()
plt.tight_layout()

plt.savefig(mypath+'results.png', dpi=300, bbox_inches='tight')

plt.show()

/home/leo/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py:6571: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
/home/leo/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py:2299: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "


In [34]:
plt.figure(figsize=(10,10))
ax=plt.subplot(2,2,1)
#plt.title('Residual', fontsize=20)
plt.tricontourf(di['y'], di['x'], di['observed_data'], 20,
                cmap='RdBu_r', vmin=np.min(di['observed_data']),
                vmax=-np.min(di['observed_data'])).ax.tick_params(labelsize=10)
plt.xlabel('$y$(m)', fontsize=10)
plt.ylabel('$x$(m)', fontsize=10)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT', pad=-315)
mpl.m2km()
clb.ax.tick_params(labelsize=13)
plt.plot(di['y'], di['x'], 'ko', markersize=.3, label='Gaussian')

# plot topography
ax=plt.subplot(2,2,2)
#plt.title('Residual', fontsize=20)
plt.tricontourf(di['y'], di['x'], di['z'], 20,
                cmap='inferno').ax.tick_params(labelsize=10)
plt.xlabel('$y$(m)', fontsize=10)
plt.ylabel('$x$(m)', fontsize=10)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT', pad=-315)
mpl.m2km()
clb.ax.tick_params(labelsize=13)
plt.plot(di['y'], di['x'], 'ko', markersize=.3, label='Gaussian')

# initial approximate
ax = plt.subplot(2,2,3, projection='3d')

# plot sides
#ax.add_collection3d(Poly3DCollection(verts_initial, alpha=0.3, 
# facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(7, -1, 100)
ax.tick_params(labelsize= 10)
ax.set_ylabel('y (km)', fontsize= 10)
ax.set_xlabel('x (km)', fontsize= 10)
ax.set_zlabel('z (km)', fontsize= 10)
#ax.yaxis.labelpad=8
#ax.zaxis.labelpad=8
#ax.xaxis.labelpad=8
ax.view_init(0, 40)

# inverse model view 1
ax = plt.subplot(2,2,4, projection='3d')

#plot sides
#ax.add_collection3d(Poly3DCollection(verts, alpha=0.3, 
#facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(7, -1, 100)
ax.tick_params(labelsize= 10)
ax.set_ylabel('y (km)', fontsize= 10)
ax.set_xlabel('x (km)', fontsize= 10)
ax.set_zlabel('z (km)', fontsize= 10)
#ax.yaxis.labelpad=8
#ax.zaxis.labelpad=8
#ax.xaxis.labelpad=8
ax.view_init(20, 135)

plt.tight_layout()

plt.savefig(mypath+'model_data.png', dpi=300, bbox_inches='tight')

plt.show()

In [23]:
di['z']

array([-489.69, -488.82, -487.58, ..., -592.48, -598.91, -604.9 ])

# Inversion 6

In [24]:
plt.figure(figsize=(6,5))
ax=mpl.subplot(1,1,1)
#plt.title('Residual', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.min(di['results'][21][-2]), vmax=np.min(di['results'][21][-2])*(-1))
plt.tricontourf(di['y'], di['x'], di['results'][21][-2], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(m)', fontsize=18)
plt.ylabel('$x$(m)', fontsize=18)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT')
mpl.m2km()
clb.ax.tick_params(labelsize=13)
inset = inset_axes(ax, width="40%", height="30%", loc=1, borderpad=0.7)
mean = np.mean(di['results'][21][-2])
std = np.std(di['results'][21][-2])
nbins=30
n, bins, patches = plt.hist(di['results'][21][-2],bins=nbins, normed=True, facecolor='blue')
plt.text(0.4, 0.96, "$\mu$ = {:.2f}\n$\sigma$ = {:.2f}".format(mean, std), 
         horizontalalignment='right',
         verticalalignment='top',
         transform = ax.transAxes, fontsize=10)
gauss = sp.norm.pdf(bins, mean, std)
plt.plot(bins, gauss, 'k--', linewidth=1., label='Gaussian')
plt.show()

In [25]:
plt.figure(figsize=(6,5))
plt.title('Convergence', fontsize = 18)
plt.xlabel('Iteration number')
plt.plot(di['results'][21][3], 'b-', label='Misfit value')
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)
plt.show()

In [26]:
x = di['x']/1000.
y = di['y']/1000.
z = di['z']/1000.

for i in range(len(di['results'][21][2])):
    di['results'][21][2][i].x /= 1000.
    di['results'][21][2][i].y /= 1000.
    di['results'][21][2][i].z1 /= 1000.
    di['results'][21][2][i].z2 /= 1000.
    

In [27]:
verts6 = mfun.plot_prisms(di['results'][21][2])

In [28]:
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts6, alpha=0.3, 
 facecolor='r', linewidths=0, edgecolors='r'))
ax.add_collection3d(Poly3DCollection(verts_true, alpha=0.3, 
 facecolor='b', linewidths=0.5, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(5, -2, 100)
ax.tick_params(labelsize= 13, pad=8)
ax.set_ylabel('Y (km)', fontsize= 17)
ax.set_xlabel('X (km)', fontsize= 17)
ax.set_zlabel('Z (km)', fontsize= 17)
#ax.set_xticklabels(np.linspace(-3, 3, 7))
#ax.set_yticklabels(np.linspace(-3, 3, 7))
#ax.set_zticklabels(np.linspace(0, 2, 9))
ax.yaxis.labelpad=13
ax.zaxis.labelpad=13
ax.xaxis.labelpad=13
ax.view_init(10, 120)
ax.autoscale_view()

plt.show()

In [29]:
np.linalg.norm(di['results'][6][2][0].props['magnetization'])

9.0

In [30]:
di['results'][6][2][0].z1

-360.0