# Visualization of inversion - Santa Catarina data

In [1228]:
import matplotlib as mpb

# show all the matplotlib backends 
mpb.rcsetup.all_backends 

# force matplotlib to use the 'Qt5Agg' backend 
mpb.use(arg='Qt5Agg', force=True)

In [1229]:
import numpy as np
import matplotlib.pyplot as plt
import cPickle as pickle
import os
import scipy.stats as sp

from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from fatiando.vis import mpl
from matplotlib import colors, ticker, cm
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from fatiando.gravmag import polyprism

In [1230]:
import sys
sys.path.insert(0, '../../code')

import mag_polyprism_functions as mfun

In [1231]:
mypath = 'up_tfa_inversion/V30_L8_inc-37_dec-18_r1500_int5_z0-900_dz700/'

In [1232]:
with open(mypath+'inversion.pickle') as w:
        di = pickle.load(w)

In [1233]:
plt.figure(figsize=(6,5))
plt.title('Observed TFA', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['observed_data'])*(-1), vmax=np.max(di['observed_data']))
plt.tricontourf(di['yp'], di['xp'], di['observed_data'], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.025, aspect=40, shrink=1)
clb.ax.tick_params(labelsize=13)
clb.ax.set_title('nT')
plt.plot(di['yp'], di['xp'], 'ok', markersize=1)
#clines = plt.tricontour(yp, xp, dobs, 20, colors='k', linewidths=0.2)
#plt.clabel(clines, fontsize=4, fmt='%3d')
mpl.m2km()
#plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1, edgecolor='black')
plt.savefig(mypath+'diorama_real_data.png', dpi=300, bbox_inches="tight")
plt.show()
#img(filename=mypath+'diorama_real_data.png', width=1000, height=1200)

In [1234]:
plt.figure(figsize=(6,5))
plt.title('Predict TFA', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['initial_data'])*(-1), vmax=np.max(di['initial_data']))
plt.tricontourf(di['yp'], di['xp'], di['initial_data'], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.025, aspect=40, shrink=1)
clb.ax.tick_params(labelsize=13)
#source = mpl.polygon(kimberlite_model['prisms'][0], '.-k', xy2ne=True)
estimate = mpl.polygon(di['initial_estimate'][0], '.-r', xy2ne=True)
#source.set_label('Outcropping polygon')
estimate.set_label('Initial estimate')
clb.ax.set_title('nT')
mpl.m2km()
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)
plt.savefig(mypath+'diorama_tfa_pred_data_true_inital.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'diorama_tfa_pred_data_true_inital.png', width=1000, height=1200)

In [1235]:
plt.figure(figsize=(6,5))
plt.title('Observed TFA', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['observed_data'])*(-1), vmax=np.max(di['observed_data']))
plt.tricontourf(di['yp'], di['xp'], di['observed_data'], 20, cmap='bwr', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.025, aspect=40, shrink=1)
clb.ax.tick_params(labelsize=13)
#source = mpl.polygon(kimberlite_model['prisms'][0], '.-k', xy2ne=True)
estimate = mpl.polygon(di['initial_estimate'][0], '.-r', xy2ne=True)
#source.set_label('Outcropping polygon')
estimate.set_label('Initial estimate')
clb.ax.set_title('nT')
mpl.m2km()
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)
plt.savefig(mypath+'diorama_tfa_obs_data_true_inital.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'diorama_tfa_obs_data_true_inital.png', width=1000, height=1200)

In [1236]:
plt.figure(figsize=(6,5))
ax=mpl.subplot(1,1,1)
plt.title('Residual', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['residual'])*(-1), vmax=np.max(di['residual']))
plt.tricontourf(di['yp'], di['xp'], di['residual'], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT')
clb.ax.tick_params(labelsize=13)
mpl.m2km()
inset = inset_axes(ax, width="40%", height="30%", loc=1, borderpad=0.7)
mean = np.mean(di['residual'])
std = np.std(di['residual'])
nbins=30
n, bins, patches = plt.hist(di['residual'],bins=nbins, normed=True, facecolor='blue')
props = dict(boxstyle='round', facecolor='wheat', alpha=0.5)
inset.text(0.7, 0.95, "$\mu$ = {:.2f}\n$\sigma$ = {:.2f}".format(mean, std),
                transform=inset.transAxes, fontsize=6,
            va='top', ha='left', bbox=props)
gauss = sp.norm.pdf(bins, mean, std)
plt.plot(bins, gauss, 'k--', linewidth=1., label='Gaussian')
plt.savefig(mypath+'diorama_tfa_residual.png', dpi=300, bbox_inches="tight")
plt.show()
#img(filename=mypath+'diorama_tfa_residual.png', width=1600, height=400)

In [1237]:
# plot
plt.figure(figsize=(25,7))
plt.subplot(1, 3, 1)
plt.title('Predict', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['observed_data'])*(-1), vmax=np.max(di['observed_data']))
plt.tricontourf(di['yp'], di['xp'], di['data_fit'],20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.tick_params(labelsize=13)
clb.ax.set_title('nT')
mpl.m2km()

plt.subplot(1, 3, 2)
plt.title('Observed', fontsize=20)
plt.tricontourf(di['yp'], di['xp'], di['observed_data'], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.tick_params(labelsize=13)
clb.ax.set_title('nT')
mpl.m2km()

plt.subplot(1, 3, 3)
plt.title('Residual', fontsize=20)
norm=mpb.colors.Normalize(vmin=np.max(di['residual'])*(-1), vmax=np.max(di['residual']))
plt.tricontourf(di['yp'], di['xp'], di['residual'], 20, cmap='RdBu_r', norm=norm).ax.tick_params(labelsize=12)
plt.xlabel('$y$(km)', fontsize=18)
plt.ylabel('$x$(km)', fontsize=18)
clb = plt.colorbar(pad=0.01, aspect=20, shrink=1)
clb.ax.set_title('nT')
clb.ax.tick_params(labelsize=13)
mpl.m2km()
plt.savefig(mypath+'diorama_tfa_fit.png', dpi=300)
plt.show()
#img(filename=mypath+'diorama_tfa_fit.png', width=1600, height=400)

In [1238]:
mean = np.mean(di['residual'])
std = np.std(di['residual'])
plt.figure(figsize=(6,5))
plt.title('Histogram', fontsize = 20)
plt.xlabel('$\mu$ = %.7f  $\sigma$ = %.7f' % (mean, std), fontsize=20)
nbins=30
n, bins, patches = plt.hist(di['residual'],bins=nbins, normed=True, color='blue')
gauss = sp.norm.pdf(bins, mean, std)
plt.plot(bins, gauss, 'k--', linewidth=2., label='Gaussian')
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)
plt.savefig(mypath+'diorama_tfa_hist.png', dpi=300)
plt.show()

#img(filename=mypath+'diorama_tfa_hist.png', width=400, height=400)

In [1239]:
plt.figure(figsize=(6,5))
plt.title('Convergence', fontsize = 18)
plt.xlabel('Iteration number')
plt.plot(di['objective'], 'b-', label='Misfit value')
plt.legend(loc=0, fontsize=12, shadow=bool, framealpha=1)

plt.savefig(mypath+'diorama_tfa_convergence.png', dpi=300)
plt.show()

#img(filename=mypath+'diorama_tfa_convergence.png', width=400, height=400)

In [1240]:
x = di['xp']/1000.
y = di['yp']/1000.
z = di['zp']/1000.

xt = di['xt']/1000.
yt = di['yt']/1000.

for i in range(len(di['prisms'])):
    di['prisms'][i].x /= 1000.
    di['prisms'][i].y /= 1000.
    di['prisms'][i].z1 /= 1000.
    di['prisms'][i].z2 /= 1000.
verts = mfun.plot_prisms(di['prisms'])


for i in range(len(di['initial_estimate'])):
    di['initial_estimate'][i].x /= 1000.
    di['initial_estimate'][i].y /= 1000.
    di['initial_estimate'][i].z1 /= 1000.
    di['initial_estimate'][i].z2 /= 1000.
verts_initial = mfun.plot_prisms(di['initial_estimate'])

In [1241]:
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts_initial, alpha=1, 
 facecolor='b', linewidths=0, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(8, -2, 100)
ax.set_ylabel('X (km)')
ax.set_xlabel('Y (km)')
ax.set_zlabel('Z (km)')
ax.view_init(10, 150)
#ax.set_xticks(np.linspace(np.min(x), np.max(x), 5), minor=True)
#ax.set_yticks(np.linspace(np.min(y), np.max(y), 5), minor=True)
#ax.set_zticks(np.linspace(6, 0, 6), minor=True)

#norm=mpb.colors.Normalize(vmin=np.min(di['residual']), vmax=np.min(di['residual'])*(-1))
#ax.tricontourf(x, y, di['residual'],
#                zdir='z', offset=-0.100, cmap='RdBu_r', norm=norm)

plt.savefig(mypath+'diorama_3d_initial_estimate.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'complex_3d_estimate.png', width=400, height=400)

In [1242]:
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_initial, alpha=1, 
 facecolor='b', linewidths=0, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(8, -2, 100)
ax.set_ylabel('X (km)')
ax.set_xlabel('Y (km)')
ax.set_zlabel('Z (km)')
ax.view_init(10, 150)
#ax.set_xticks(np.linspace(np.min(x), np.max(x)-2, 5), minor=True)
#ax.set_yticks(np.linspace(np.min(y)+2, np.max(y)-1, 5), minor=True)
#ax.set_zticks(np.linspace(6, 0, 6), minor=True)

#norm=mpb.colors.Normalize(vmin=np.min(di['residual']), vmax=np.min(di['residual'])*(-1))
#ax.tricontourf(x, y, di['residual'],
#                zdir='z', offset=-0.100, cmap='RdBu_r', norm=norm)

plt.savefig(mypath+'diorama_3d_estimate.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'complex_3d_estimate.png', width=400, height=400)

In [1243]:
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111, projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
ax.add_collection3d(Poly3DCollection(verts_initial, alpha=0.3, 
 facecolor='b', linewidths=0, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(8, -2, 100)
ax.set_ylabel('X (km)')
ax.set_xlabel('Y (km)')
ax.set_zlabel('Z (km)')
ax.view_init(-10, 30)
#ax.set_xticks(np.linspace(np.min(x), np.max(x)-2, 5), minor=True)
#ax.set_yticks(np.linspace(np.min(y)+2, np.max(y)-1, 5), minor=True)
#ax.set_zticks(np.linspace(6, 0, 6), minor=True)

#norm=mpb.colors.Normalize(vmin=np.min(di['residual']), vmax=np.min(di['residual'])*(-1))
#ax.tricontourf(x, y, di['residual'],
#                zdir='z', offset=-0.100, cmap='RdBu_r', norm=norm)

plt.savefig(mypath+'diorama_3d_estimate2.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'complex_3d_estimate.png', width=400, height=400)

In [1244]:
fig = plt.figure(figsize=(10,8))
ax = fig.gca(projection='3d')

# plot sides
ax.add_collection3d(Poly3DCollection(verts, alpha=0.3, 
 facecolor='r', linewidths=0.5, edgecolors='k'))
#ax.add_collection3d(Poly3DCollection(verts_initial, alpha=1, 
# facecolor='b', linewidths=0, edgecolors='k'))

ax.set_ylim(np.min(x), np.max(x), 100)
ax.set_xlim(np.min(y), np.max(y), 100)
ax.set_zlim(8, -2, 100)
ax.set_ylabel('X (km)')
ax.set_xlabel('Y (km)')
ax.set_zlabel('Z (km)')
ax.view_init(20, 200)
#ax.set_xticks(np.linspace(np.min(x), np.max(x)-2, 4), minor=True)
#ax.set_yticks(np.linspace(np.min(y)+2, np.max(y)-1, 5), minor=True)
#ax.set_zticks(np.linspace(6, 0, 6), minor=True)

#norm=mpb.colors.Normalize(vmin=np.min(di['residual']), vmax=np.min(di['residual'])*(-1))
#ax.tricontourf(y, x, di['residual'],
#                zdir='z', offset=-2.00, cmap='RdBu_r', norm=norm)

#ax.plot_trisurf(yt, xt, -di['topography']/1000., linewidth=0.2, antialiased=True, cmap='inferno')

plt.savefig(mypath+'diorama_3d_estimate3.png', dpi=300, bbox_inches="tight")
plt.show()

#img(filename=mypath+'complex_3d_estimate.png', width=400, height=400)

In [1245]:
o = np.ones((5,5))
q = np.linspace(1,5,5)
Q = np.diag(q)

In [1246]:
np.dot(o,Q)

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [1247]:
o*Q.T

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [1248]:
np.dot(Q,o)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [1249]:
o.T*q

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [1250]:
np.linalg.solve(Q, q)

array([1., 1., 1., 1., 1.])